"""add embedding to article chunks

Revision ID: 45408481c8a2
Revises: 6756ca15eed0
Create Date: 2026-09-16 18:41:20.950857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from pgvector.sqlalchemy import VECTOR


# revision identifiers, used by Alembic.
revision: str = '45408481c8a2'
down_revision: Union[str, Sequence[str], None] = '6756ca15eed0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article_chunks', sa.Column('embedding', VECTOR(1536), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article_chunks', 'embedding')
    # ### end Alembic commands ###
