"""create guest quotas

Revision ID: 70e1e700e569
Revises: 65a0c1dce751
Create Date: 2026-09-25 22:32:10.400981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '70e1e700e569'
down_revision: Union[str, Sequence[str], None] = '65a0c1dce751'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guest_quotas',
    sa.Column('anonymous_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('anonymous_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guest_quotas')
    # ### end Alembic commands ###
