"""add translated article fields

Revision ID: 7ac1b5a6d92c
Revises: aa33a100b469
Create Date: 2026-09-13 21:44:38.194213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ac1b5a6d92c'
down_revision: Union[str, Sequence[str], None] = 'aa33a100b469'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('translated_title', sa.Text(), nullable=True))
    op.add_column('articles', sa.Column('translated_description', sa.Text(), nullable=True))
    op.add_column('articles', sa.Column('translated_content', sa.Text(), nullable=True))
    op.add_column('articles', sa.Column('translated_language', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'translated_language')
    op.drop_column('articles', 'translated_content')
    op.drop_column('articles', 'translated_description')
    op.drop_column('articles', 'translated_title')
    # ### end Alembic commands ###
