"""update type field created_at

Revision ID: 8be2eb9882f4
Revises: 7ac1b5a6d92c
Create Date: 2026-09-14 09:19:36.191167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8be2eb9882f4'
down_revision: Union[str, Sequence[str], None] = '7ac1b5a6d92c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
